add_custom_target(mcuboot_shared_property_target)
set_property(TARGET mcuboot_shared_property_target  PROPERTY KERNEL_HEX_NAME;zephyr.hex)
set_property(TARGET mcuboot_shared_property_target  PROPERTY ZEPHYR_BINARY_DIR;/work/nrfconnect/nrf/applications/matter_weather_station/debug/mcuboot/zephyr)
set_property(TARGET mcuboot_shared_property_target  PROPERTY KERNEL_ELF_NAME;zephyr.elf)
set_property(TARGET mcuboot_shared_property_target  PROPERTY BUILD_BYPRODUCTS;/work/nrfconnect/nrf/applications/matter_weather_station/debug/mcuboot/zephyr/zephyr.hex;/work/nrfconnect/nrf/applications/matter_weather_station/debug/mcuboot/zephyr/zephyr.elf)
set_property(TARGET mcuboot_shared_property_target  PROPERTY SIGNATURE_KEY_FILE;root-rsa-2048.pem)
set_property(TARGET mcuboot_shared_property_target APPEND PROPERTY PM_YML_DEP_FILES;/work/nrfconnect/bootloader/mcuboot/boot/zephyr/pm.yml)
set_property(TARGET mcuboot_shared_property_target APPEND PROPERTY PM_YML_FILES;/work/nrfconnect/nrf/applications/matter_weather_station/debug/mcuboot/zephyr/include/generated/pm.yml)
set_property(TARGET mcuboot_shared_property_target APPEND PROPERTY PM_YML_DEP_FILES;/work/nrfconnect/nrf/subsys/partition_manager/pm.yml.pcd)
set_property(TARGET mcuboot_shared_property_target APPEND PROPERTY PM_YML_FILES;/work/nrfconnect/nrf/applications/matter_weather_station/debug/mcuboot/modules/nrf/subsys/partition_manager/pm.yml.pcd)
set_property(TARGET mcuboot_shared_property_target  PROPERTY NRF53_MULTI_IMAGE_UPDATE;y)
set_property(TARGET mcuboot_shared_property_target  PROPERTY RAM_FLASH_ADDR;0x0)
set_property(TARGET mcuboot_shared_property_target  PROPERTY RAM_FLASH_SIZE;0x40000)
set_property(TARGET mcuboot_shared_property_target  PROPERTY RAM_FLASH_LABEL;nordic_ram_flash_controller)
